### ISSUE TITLE
We cannot fold on top of this native query. Please modify the native query or remove the 'EnableFolding' option

### ISSUE THREAD

**Issue by oscarrudnas** [mscottsewell/Power-BI-D365-Sales#1]
This happens when loading data in contoso sales.pbit on all queries except "Owner" table.
Changing the query to [EnableFolding=false] gives error Microsoft SQL: Unexpected end of file occurred. Line:47, Position:9
on query "Opportunity"

**Comment by oscarrudnas** [comment]
> This happens when loading data in contoso sales.pbit on all queries except "Owner" table. Changing the query to [EnableFolding=false] gives error Microsoft SQL: Unexpected end of file occurred. Line:47, Position:9 on query "Opportunity"

Changed the parameter "monthsofhistory" from negative (-6) to positive (6).

**Comment by mscottsewell** [comment]
I'll take a look this morning. Thank you for the info.

**Comment by mscottsewell** [comment]
'Months of history' should always be a positive number. - I'll look at adding "Number.Abs()" around the value to force it to be positive if this becomes a common question.
